\set ON_ERROR_STOP on

SET client_min_messages = warning;
SET timezone = 'UTC';
SET statement_timeout = 0;

DO $$
BEGIN
  IF current_database() <> 'schemanaut_demo' THEN
    RAISE EXCEPTION 'This fixture must run against schemanaut_demo, got %', current_database();
  END IF;
END
$$;

BEGIN;
SET LOCAL synchronous_commit = off;
SELECT setseed(0.4242);

CREATE SCHEMA iam;
CREATE SCHEMA catalog;
CREATE SCHEMA commerce;
CREATE SCHEMA streaming;
CREATE SCHEMA analytics;

CREATE TYPE iam.user_status AS ENUM ('active', 'locked', 'disabled', 'pending');
CREATE TYPE commerce.order_status AS ENUM (
  'pending', 'paid', 'processing', 'shipped', 'completed', 'cancelled',
  'partially_refunded', 'refunded'
);
CREATE TYPE commerce.payment_status AS ENUM (
  'pending', 'succeeded', 'failed', 'partially_refunded', 'refunded'
);
CREATE TYPE commerce.shipment_status AS ENUM (
  'created', 'picked', 'in_transit', 'delivered', 'exception', 'returned'
);
CREATE TYPE commerce.refund_status AS ENUM ('requested', 'approved', 'processing', 'completed', 'rejected');

CREATE TABLE iam.users (
  user_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  phone text,
  password_hash text NOT NULL,
  display_name text NOT NULL,
  status iam.user_status NOT NULL DEFAULT 'active',
  locale varchar(12) NOT NULL DEFAULT 'zh-CN',
  marketing_opt_in boolean NOT NULL DEFAULT false,
  profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  registered_at timestamptz NOT NULL,
  last_login_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT users_email_shape CHECK (position('@' in email) > 1),
  CONSTRAINT users_profile_object CHECK (jsonb_typeof(profile) = 'object')
);

CREATE UNIQUE INDEX users_email_ci_uq ON iam.users (lower(email));
CREATE INDEX users_status_registered_idx ON iam.users (status, registered_at DESC);
CREATE INDEX users_profile_gin_idx ON iam.users USING gin (profile);

CREATE TABLE iam.roles (
  role_id smallint PRIMARY KEY,
  role_code varchar(40) NOT NULL UNIQUE,
  role_name varchar(80) NOT NULL,
  permissions jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT roles_permissions_array CHECK (jsonb_typeof(permissions) = 'array')
);

CREATE TABLE iam.user_roles (
  user_id bigint NOT NULL REFERENCES iam.users(user_id) ON DELETE CASCADE,
  role_id smallint NOT NULL REFERENCES iam.roles(role_id),
  granted_by bigint REFERENCES iam.users(user_id),
  granted_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  expires_at timestamptz,
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT user_roles_expiry CHECK (expires_at IS NULL OR expires_at > granted_at)
);

CREATE TABLE iam.user_sessions (
  session_id uuid PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES iam.users(user_id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  device jsonb NOT NULL,
  ip_address inet,
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL,
  revoked_at timestamptz,
  CONSTRAINT sessions_time_order CHECK (expires_at > created_at),
  CONSTRAINT sessions_device_object CHECK (jsonb_typeof(device) = 'object')
);

CREATE INDEX user_sessions_user_active_idx ON iam.user_sessions (user_id, last_seen_at DESC)
WHERE revoked_at IS NULL;

CREATE TABLE iam.login_events (
  login_event_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES iam.users(user_id) ON DELETE SET NULL,
  session_id uuid REFERENCES iam.user_sessions(session_id) ON DELETE SET NULL,
  event_type varchar(30) NOT NULL,
  success boolean NOT NULL,
  failure_reason varchar(120),
  ip_address inet,
  user_agent text,
  geo jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL,
  CONSTRAINT login_event_type_check CHECK (event_type IN ('password', 'sms', 'oauth', 'refresh', 'logout')),
  CONSTRAINT login_failure_reason_check CHECK (success OR failure_reason IS NOT NULL)
);

CREATE INDEX login_events_user_time_idx ON iam.login_events (user_id, occurred_at DESC);
CREATE INDEX login_events_failures_idx ON iam.login_events (occurred_at DESC) WHERE NOT success;

CREATE TABLE catalog.categories (
  category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id integer REFERENCES catalog.categories(category_id),
  category_code varchar(40) NOT NULL UNIQUE,
  category_name varchar(100) NOT NULL,
  path text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  attributes_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX categories_parent_idx ON catalog.categories (parent_id, sort_order);

CREATE TABLE catalog.products (
  product_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  product_sku varchar(64) NOT NULL UNIQUE,
  category_id integer NOT NULL REFERENCES catalog.categories(category_id),
  product_name text NOT NULL,
  brand varchar(80) NOT NULL,
  status varchar(20) NOT NULL,
  base_price numeric(12,2) NOT NULL,
  cost_price numeric(12,2) NOT NULL,
  attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
  tags text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT products_status_check CHECK (status IN ('draft', 'active', 'out_of_stock', 'archived')),
  CONSTRAINT products_price_check CHECK (base_price >= 0 AND cost_price >= 0 AND base_price >= cost_price),
  CONSTRAINT products_attributes_object CHECK (jsonb_typeof(attributes) = 'object')
);

CREATE INDEX products_category_status_idx ON catalog.products (category_id, status);
CREATE INDEX products_attributes_gin_idx ON catalog.products USING gin (attributes);
CREATE INDEX products_tags_gin_idx ON catalog.products USING gin (tags);

CREATE TABLE catalog.product_variants (
  variant_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES catalog.products(product_id) ON DELETE CASCADE,
  variant_sku varchar(80) NOT NULL UNIQUE,
  specs jsonb NOT NULL,
  price_delta numeric(10,2) NOT NULL DEFAULT 0,
  weight_grams integer NOT NULL,
  barcode varchar(40) UNIQUE,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT variants_weight_check CHECK (weight_grams > 0),
  CONSTRAINT variants_specs_object CHECK (jsonb_typeof(specs) = 'object')
);

CREATE INDEX product_variants_product_idx ON catalog.product_variants (product_id, active);
CREATE INDEX product_variants_specs_gin_idx ON catalog.product_variants USING gin (specs);

CREATE TABLE commerce.warehouses (
  warehouse_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  warehouse_code varchar(30) NOT NULL UNIQUE,
  warehouse_name varchar(100) NOT NULL,
  region varchar(30) NOT NULL,
  address jsonb NOT NULL,
  timezone varchar(40) NOT NULL DEFAULT 'Asia/Shanghai',
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE commerce.inventory (
  warehouse_id integer NOT NULL REFERENCES commerce.warehouses(warehouse_id),
  variant_id bigint NOT NULL REFERENCES catalog.product_variants(variant_id),
  available_quantity integer NOT NULL,
  reserved_quantity integer NOT NULL,
  reorder_point integer NOT NULL,
  safety_stock integer NOT NULL,
  version integer NOT NULL DEFAULT 1,
  updated_at timestamptz NOT NULL,
  PRIMARY KEY (warehouse_id, variant_id),
  CONSTRAINT inventory_nonnegative_check CHECK (
    available_quantity >= 0 AND reserved_quantity >= 0 AND reorder_point >= 0 AND safety_stock >= 0
  )
);

CREATE INDEX inventory_variant_idx ON commerce.inventory (variant_id);
CREATE INDEX inventory_low_stock_idx ON commerce.inventory (warehouse_id, available_quantity)
WHERE available_quantity <= reorder_point;

CREATE TABLE commerce.orders (
  order_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_no varchar(40) NOT NULL UNIQUE,
  user_id bigint NOT NULL REFERENCES iam.users(user_id),
  status commerce.order_status NOT NULL,
  currency char(3) NOT NULL DEFAULT 'CNY',
  subtotal_amount numeric(14,2) NOT NULL DEFAULT 0,
  discount_amount numeric(14,2) NOT NULL DEFAULT 0,
  shipping_fee numeric(14,2) NOT NULL DEFAULT 0,
  tax_amount numeric(14,2) NOT NULL DEFAULT 0,
  total_amount numeric(14,2) GENERATED ALWAYS AS (
    subtotal_amount - discount_amount + shipping_fee + tax_amount
  ) STORED,
  coupon_code varchar(40),
  shipping_address jsonb NOT NULL,
  channel varchar(20) NOT NULL,
  risk_score numeric(5,2) NOT NULL DEFAULT 0,
  notes text,
  ordered_at timestamptz NOT NULL,
  paid_at timestamptz,
  cancelled_at timestamptz,
  updated_at timestamptz NOT NULL,
  CONSTRAINT orders_amount_check CHECK (
    subtotal_amount >= 0 AND discount_amount >= 0 AND shipping_fee >= 0 AND tax_amount >= 0
      AND discount_amount <= subtotal_amount
  ),
  CONSTRAINT orders_channel_check CHECK (channel IN ('web', 'app', 'mini_program', 'api')),
  CONSTRAINT orders_risk_score_check CHECK (risk_score BETWEEN 0 AND 100),
  CONSTRAINT orders_shipping_address_object CHECK (jsonb_typeof(shipping_address) = 'object')
);

CREATE INDEX orders_user_time_idx ON commerce.orders (user_id, ordered_at DESC);
CREATE INDEX orders_status_time_idx ON commerce.orders (status, ordered_at DESC);
CREATE INDEX orders_shipping_address_gin_idx ON commerce.orders USING gin (shipping_address);

CREATE TABLE commerce.order_items (
  order_item_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES commerce.orders(order_id) ON DELETE CASCADE,
  variant_id bigint NOT NULL REFERENCES catalog.product_variants(variant_id),
  product_name_snapshot text NOT NULL,
  sku_snapshot varchar(80) NOT NULL,
  quantity integer NOT NULL,
  unit_price numeric(12,2) NOT NULL,
  discount_amount numeric(12,2) NOT NULL DEFAULT 0,
  line_total numeric(14,2) GENERATED ALWAYS AS (unit_price * quantity - discount_amount) STORED,
  attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL,
  CONSTRAINT order_items_quantity_check CHECK (quantity > 0),
  CONSTRAINT order_items_amount_check CHECK (
    unit_price >= 0 AND discount_amount >= 0 AND discount_amount <= unit_price * quantity
  )
);

CREATE INDEX order_items_order_idx ON commerce.order_items (order_id);
CREATE INDEX order_items_variant_idx ON commerce.order_items (variant_id, created_at DESC);

CREATE TABLE commerce.payments (
  payment_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  payment_no varchar(48) NOT NULL UNIQUE,
  order_id bigint NOT NULL REFERENCES commerce.orders(order_id),
  provider varchar(30) NOT NULL,
  status commerce.payment_status NOT NULL,
  amount numeric(14,2) NOT NULL,
  transaction_id varchar(80),
  request_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  response_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  paid_at timestamptz,
  refunded_at timestamptz,
  created_at timestamptz NOT NULL,
  CONSTRAINT payments_amount_check CHECK (amount >= 0),
  CONSTRAINT payments_provider_check CHECK (provider IN ('alipay', 'wechat_pay', 'unionpay', 'stripe'))
);

CREATE INDEX payments_order_idx ON commerce.payments (order_id);
CREATE INDEX payments_status_created_idx ON commerce.payments (status, created_at DESC);

CREATE TABLE commerce.shipments (
  shipment_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  shipment_no varchar(48) NOT NULL UNIQUE,
  order_id bigint NOT NULL REFERENCES commerce.orders(order_id),
  warehouse_id integer NOT NULL REFERENCES commerce.warehouses(warehouse_id),
  carrier varchar(40) NOT NULL,
  tracking_no varchar(80) UNIQUE,
  status commerce.shipment_status NOT NULL,
  package_info jsonb NOT NULL,
  route_events jsonb NOT NULL DEFAULT '[]'::jsonb,
  shipped_at timestamptz,
  delivered_at timestamptz,
  updated_at timestamptz NOT NULL,
  CONSTRAINT shipments_route_array CHECK (jsonb_typeof(route_events) = 'array'),
  CONSTRAINT shipments_time_order CHECK (
    delivered_at IS NULL OR shipped_at IS NULL OR delivered_at >= shipped_at
  )
);

CREATE INDEX shipments_order_idx ON commerce.shipments (order_id);
CREATE INDEX shipments_status_updated_idx ON commerce.shipments (status, updated_at DESC);

CREATE TABLE commerce.refunds (
  refund_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  refund_no varchar(48) NOT NULL UNIQUE,
  order_id bigint NOT NULL REFERENCES commerce.orders(order_id),
  payment_id bigint NOT NULL REFERENCES commerce.payments(payment_id),
  order_item_id bigint REFERENCES commerce.order_items(order_item_id),
  status commerce.refund_status NOT NULL,
  reason_code varchar(40) NOT NULL,
  amount numeric(14,2) NOT NULL,
  evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
  requested_at timestamptz NOT NULL,
  completed_at timestamptz,
  CONSTRAINT refunds_amount_check CHECK (amount > 0),
  CONSTRAINT refunds_evidence_array CHECK (jsonb_typeof(evidence) = 'array')
);

CREATE INDEX refunds_order_idx ON commerce.refunds (order_id, requested_at DESC);
CREATE INDEX refunds_status_idx ON commerce.refunds (status, requested_at DESC);

CREATE TABLE commerce.promotions (
  promotion_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  promo_code varchar(40) NOT NULL UNIQUE,
  promotion_name varchar(120) NOT NULL,
  promotion_type varchar(30) NOT NULL,
  rules jsonb NOT NULL,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  budget_amount numeric(14,2) NOT NULL,
  used_count integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  CONSTRAINT promotions_type_check CHECK (promotion_type IN ('percentage', 'fixed', 'bundle', 'free_shipping')),
  CONSTRAINT promotions_time_check CHECK (ends_at > starts_at),
  CONSTRAINT promotions_budget_check CHECK (budget_amount >= 0),
  CONSTRAINT promotions_rules_object CHECK (jsonb_typeof(rules) = 'object')
);

CREATE INDEX promotions_active_time_idx ON commerce.promotions (active, starts_at, ends_at);

CREATE TABLE streaming.raw_kafka_events (
  kafka_event_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  topic varchar(120) NOT NULL,
  partition_no integer NOT NULL,
  offset_no bigint NOT NULL,
  event_key text,
  event_type varchar(60),
  headers jsonb NOT NULL DEFAULT '{}'::jsonb,
  value jsonb NOT NULL,
  event_time timestamptz,
  ingested_at timestamptz NOT NULL,
  schema_version integer NOT NULL DEFAULT 1,
  parse_status varchar(20) NOT NULL DEFAULT 'valid',
  UNIQUE (topic, partition_no, offset_no),
  CONSTRAINT kafka_partition_check CHECK (partition_no >= 0),
  CONSTRAINT kafka_offset_check CHECK (offset_no >= 0),
  CONSTRAINT kafka_value_object CHECK (jsonb_typeof(value) = 'object'),
  CONSTRAINT kafka_parse_status_check CHECK (parse_status IN ('valid', 'invalid', 'partial', 'duplicate'))
);

CREATE INDEX raw_kafka_topic_time_idx ON streaming.raw_kafka_events (topic, event_time DESC);
CREATE INDEX raw_kafka_event_type_idx ON streaming.raw_kafka_events (event_type, ingested_at DESC);
CREATE INDEX raw_kafka_value_gin_idx ON streaming.raw_kafka_events USING gin (value);
CREATE INDEX raw_kafka_invalid_idx ON streaming.raw_kafka_events (ingested_at DESC)
WHERE parse_status <> 'valid';

CREATE TABLE streaming.consumer_offsets (
  consumer_group varchar(120) NOT NULL,
  topic varchar(120) NOT NULL,
  partition_no integer NOT NULL,
  committed_offset bigint NOT NULL,
  high_watermark bigint NOT NULL,
  lag bigint GENERATED ALWAYS AS (high_watermark - committed_offset) STORED,
  consumer_instance varchar(120),
  updated_at timestamptz NOT NULL,
  PRIMARY KEY (consumer_group, topic, partition_no),
  CONSTRAINT consumer_offsets_order_check CHECK (
    partition_no >= 0 AND committed_offset >= 0 AND high_watermark >= committed_offset
  )
);

CREATE INDEX consumer_offsets_lag_idx ON streaming.consumer_offsets (lag DESC);

CREATE TABLE streaming.dead_letter_events (
  dlq_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  source_event_id bigint REFERENCES streaming.raw_kafka_events(kafka_event_id),
  source_topic varchar(120) NOT NULL,
  error_code varchar(60) NOT NULL,
  error_message text NOT NULL,
  retry_count integer NOT NULL DEFAULT 0,
  payload jsonb NOT NULL,
  first_seen_at timestamptz NOT NULL,
  last_retry_at timestamptz,
  resolved_at timestamptz,
  CONSTRAINT dlq_retry_count_check CHECK (retry_count >= 0)
);

CREATE INDEX dead_letter_unresolved_idx ON streaming.dead_letter_events (first_seen_at DESC)
WHERE resolved_at IS NULL;
CREATE INDEX dead_letter_error_code_idx ON streaming.dead_letter_events (error_code, first_seen_at DESC);

CREATE TABLE analytics.daily_product_metrics (
  metric_date date NOT NULL,
  product_id bigint NOT NULL REFERENCES catalog.products(product_id),
  view_count integer NOT NULL,
  cart_count integer NOT NULL,
  order_count integer NOT NULL,
  units_sold integer NOT NULL,
  gross_revenue numeric(16,2) NOT NULL,
  refund_amount numeric(16,2) NOT NULL,
  conversion_rate numeric(8,6) GENERATED ALWAYS AS (
    CASE WHEN view_count = 0 THEN 0 ELSE order_count::numeric / view_count END
  ) STORED,
  updated_at timestamptz NOT NULL,
  PRIMARY KEY (metric_date, product_id),
  CONSTRAINT daily_metrics_counts_check CHECK (
    view_count >= 0 AND cart_count >= 0 AND order_count >= 0 AND units_sold >= 0
  ),
  CONSTRAINT daily_metrics_amounts_check CHECK (gross_revenue >= 0 AND refund_amount >= 0)
);

CREATE INDEX daily_product_metrics_product_idx ON analytics.daily_product_metrics (product_id, metric_date DESC);

INSERT INTO iam.roles (role_id, role_code, role_name, permissions) VALUES
  (1, 'customer', '普通客户', '["catalog:read", "order:create", "order:read:self"]'),
  (2, 'admin', '平台管理员', '["*"]'),
  (3, 'warehouse_operator', '仓库操作员', '["inventory:read", "inventory:write", "shipment:write"]'),
  (4, 'support_agent', '客服专员', '["order:read", "refund:review", "user:read"]');

INSERT INTO iam.users (
  email, phone, password_hash, display_name, status, locale, marketing_opt_in,
  profile, registered_at, last_login_at
)
SELECT
  'user' || lpad(i::text, 5, '0') || '@example.com',
  CASE WHEN i % 9 = 0 THEN NULL ELSE '138' || lpad((10000000 + i)::text, 8, '0') END,
  '$demo$' || md5('password-' || i::text),
  CASE WHEN i % 7 = 0 THEN '会员-' || i ELSE 'Demo User ' || i END,
  (CASE
    WHEN i % 97 = 0 THEN 'locked'
    WHEN i % 131 = 0 THEN 'disabled'
    WHEN i % 173 = 0 THEN 'pending'
    ELSE 'active'
  END)::iam.user_status,
  CASE WHEN i % 11 = 0 THEN 'en-US' ELSE 'zh-CN' END,
  i % 3 = 0,
  jsonb_build_object(
    'level', CASE WHEN i % 20 = 0 THEN 'vip' WHEN i % 5 = 0 THEN 'gold' ELSE 'standard' END,
    'points', (i * 37) % 20000,
    'preferred_categories', jsonb_build_array('category-' || ((i % 20) + 1), 'category-' || (((i + 7) % 20) + 1)),
    'source', CASE WHEN i % 4 = 0 THEN 'campaign' ELSE 'organic' END
  ),
  clock_timestamp() - ((i % 720) * interval '1 day') - ((i % 24) * interval '1 hour'),
  clock_timestamp() - ((i % 30) * interval '1 day') - ((i % 12) * interval '1 hour')
FROM generate_series(1, 5000) AS g(i);

INSERT INTO iam.user_roles (user_id, role_id, granted_by, granted_at)
SELECT user_id, 1, NULL, registered_at FROM iam.users;

INSERT INTO iam.user_roles (user_id, role_id, granted_by, granted_at)
SELECT user_id, 2, 1, registered_at + interval '1 day' FROM iam.users WHERE user_id % 1000 = 0;

INSERT INTO iam.user_roles (user_id, role_id, granted_by, granted_at)
SELECT user_id, 3, 1, registered_at + interval '2 days' FROM iam.users WHERE user_id % 250 = 0;

INSERT INTO iam.user_roles (user_id, role_id, granted_by, granted_at)
SELECT user_id, 4, 1, registered_at + interval '2 days' FROM iam.users WHERE user_id % 400 = 0;

INSERT INTO iam.user_sessions (
  session_id, user_id, token_hash, device, ip_address, created_at, expires_at, last_seen_at, revoked_at
)
SELECT
  md5('session-' || i::text)::uuid,
  ((i - 1) % 5000) + 1,
  md5('token-' || i::text),
  jsonb_build_object(
    'type', CASE WHEN i % 3 = 0 THEN 'mobile' ELSE 'desktop' END,
    'os', CASE WHEN i % 4 = 0 THEN 'iOS' WHEN i % 4 = 1 THEN 'Android' WHEN i % 4 = 2 THEN 'Windows' ELSE 'macOS' END,
    'app_version', '2.' || (i % 8) || '.' || (i % 20)
  ),
  ('10.' || (i % 250) || '.' || ((i * 7) % 250) || '.' || ((i * 13) % 250))::inet,
  clock_timestamp() - ((i % 60) * interval '1 day'),
  clock_timestamp() + ((30 - (i % 60)) * interval '1 day'),
  clock_timestamp() - ((i % 72) * interval '1 hour'),
  CASE WHEN i % 23 = 0 THEN clock_timestamp() - ((i % 15) * interval '1 day') END
FROM generate_series(1, 10000) AS g(i);

INSERT INTO iam.login_events (
  user_id, session_id, event_type, success, failure_reason, ip_address, user_agent, geo, occurred_at
)
SELECT
  ((i - 1) % 5000) + 1,
  md5('session-' || (((i - 1) % 10000) + 1)::text)::uuid,
  (ARRAY['password', 'sms', 'oauth', 'refresh', 'logout'])[(i % 5) + 1],
  i % 17 <> 0,
  CASE WHEN i % 17 = 0 THEN (ARRAY['invalid_password', 'expired_code', 'risk_blocked'])[(i % 3) + 1] END,
  ('172.16.' || (i % 250) || '.' || ((i * 19) % 250))::inet,
  CASE WHEN i % 3 = 0 THEN 'SchemaNautDemoApp/2.4 (iPhone)' ELSE 'Mozilla/5.0 Demo Browser' END,
  jsonb_build_object(
    'country', 'CN',
    'province', (ARRAY['上海', '北京', '广东', '浙江', '四川'])[(i % 5) + 1],
    'city', (ARRAY['上海', '北京', '深圳', '杭州', '成都'])[(i % 5) + 1]
  ),
  clock_timestamp() - ((i % 90) * interval '1 day') - ((i % 86400) * interval '1 second')
FROM generate_series(1, 50000) AS g(i);

INSERT INTO catalog.categories (
  category_id, parent_id, category_code, category_name, path, sort_order, attributes_schema
)
SELECT
  i,
  NULL,
  'root-' || lpad(i::text, 2, '0'),
  (ARRAY['数码', '家电', '服饰', '食品', '美妆', '母婴', '家居', '运动', '图书', '汽车用品'])[i],
  '/' || i,
  i,
  jsonb_build_object('required', jsonb_build_array('brand'))
FROM generate_series(1, 10) AS g(i);

INSERT INTO catalog.categories (
  category_id, parent_id, category_code, category_name, path, sort_order, attributes_schema
)
SELECT
  i,
  ((i - 11) % 10) + 1,
  'leaf-' || lpad(i::text, 2, '0'),
  '细分类目-' || i,
  '/' || (((i - 11) % 10) + 1) || '/' || i,
  i,
  jsonb_build_object('required', jsonb_build_array('color', 'size'), 'version', 1)
FROM generate_series(11, 30) AS g(i);

INSERT INTO catalog.products (
  product_sku, category_id, product_name, brand, status, base_price, cost_price,
  attributes, tags, created_at, updated_at
)
SELECT
  'SPU-' || lpad(i::text, 7, '0'),
  11 + (i % 20),
  CASE WHEN i % 6 = 0 THEN '旗舰商品-' || i ELSE 'Demo Product ' || i END,
  'Brand-' || ((i % 40) + 1),
  CASE WHEN i % 101 = 0 THEN 'archived' WHEN i % 37 = 0 THEN 'out_of_stock' ELSE 'active' END,
  round((29 + (i % 3000) * 0.73)::numeric, 2),
  round((12 + (i % 1800) * 0.41)::numeric, 2),
  jsonb_build_object(
    'color', (ARRAY['black', 'white', 'red', 'blue', 'green'])[(i % 5) + 1],
    'material', (ARRAY['metal', 'plastic', 'cotton', 'wood'])[(i % 4) + 1],
    'origin', (ARRAY['上海', '深圳', '杭州', '成都'])[(i % 4) + 1],
    'warranty_months', (i % 36) + 1
  ),
  ARRAY['demo', CASE WHEN i % 10 = 0 THEN 'hot' ELSE 'standard' END, 'category-' || (11 + (i % 20))],
  clock_timestamp() - ((i % 500) * interval '1 day'),
  clock_timestamp() - ((i % 45) * interval '1 day')
FROM generate_series(1, 2000) AS g(i);

INSERT INTO catalog.product_variants (
  product_id, variant_sku, specs, price_delta, weight_grams, barcode, active
)
SELECT
  ((i - 1) / 3) + 1,
  'SKU-' || lpad(i::text, 8, '0'),
  jsonb_build_object(
    'color', (ARRAY['black', 'white', 'blue'])[((i - 1) % 3) + 1],
    'size', (ARRAY['S', 'M', 'L', 'XL'])[(i % 4) + 1]
  ),
  ((i - 1) % 3) * 10,
  100 + (i % 4900),
  '69' || lpad(i::text, 11, '0'),
  i % 97 <> 0
FROM generate_series(1, 6000) AS g(i);

INSERT INTO commerce.warehouses (
  warehouse_code, warehouse_name, region, address, timezone
)
SELECT
  'WH-' || i,
  (ARRAY['华东中心仓', '华北中心仓', '华南中心仓', '西南中心仓', '跨境保税仓'])[i],
  (ARRAY['east', 'north', 'south', 'southwest', 'cross_border'])[i],
  jsonb_build_object(
    'province', (ARRAY['上海', '北京', '广东', '四川', '浙江'])[i],
    'city', (ARRAY['上海', '北京', '广州', '成都', '宁波'])[i],
    'detail', '示例仓储园区 ' || i || ' 号'
  ),
  'Asia/Shanghai'
FROM generate_series(1, 5) AS g(i);

INSERT INTO commerce.inventory (
  warehouse_id, variant_id, available_quantity, reserved_quantity,
  reorder_point, safety_stock, version, updated_at
)
SELECT
  w.warehouse_id,
  v.variant_id,
  (v.variant_id * 13 + w.warehouse_id * 17) % 500,
  (v.variant_id + w.warehouse_id) % 35,
  30 + ((v.variant_id + w.warehouse_id) % 40),
  10 + ((v.variant_id + w.warehouse_id) % 20),
  1 + ((v.variant_id + w.warehouse_id) % 15),
  clock_timestamp() - (((v.variant_id + w.warehouse_id) % 72) * interval '1 hour')
FROM commerce.warehouses AS w
CROSS JOIN catalog.product_variants AS v;

INSERT INTO commerce.orders (
  order_no, user_id, status, currency, subtotal_amount, discount_amount,
  shipping_fee, tax_amount, coupon_code, shipping_address, channel,
  risk_score, notes, ordered_at, paid_at, cancelled_at, updated_at
)
SELECT
  'ORD-' || to_char(clock_timestamp(), 'YYYYMM') || '-' || lpad(i::text, 8, '0'),
  ((i - 1) % 5000) + 1,
  (CASE
    WHEN i % 20 = 0 THEN 'cancelled'
    WHEN i % 20 = 1 THEN 'pending'
    WHEN i % 20 = 2 THEN 'refunded'
    WHEN i % 20 = 3 THEN 'partially_refunded'
    WHEN i % 20 BETWEEN 4 AND 5 THEN 'processing'
    WHEN i % 20 BETWEEN 6 AND 9 THEN 'paid'
    WHEN i % 20 BETWEEN 10 AND 14 THEN 'shipped'
    ELSE 'completed'
  END)::commerce.order_status,
  CASE WHEN i % 50 = 0 THEN 'USD' ELSE 'CNY' END,
  0, 0, 0, 0,
  CASE WHEN i % 7 = 0 THEN 'PROMO-' || ((i % 24) + 1) END,
  jsonb_build_object(
    'recipient', '收货人-' || ((i - 1) % 5000 + 1),
    'phone', '139' || lpad((20000000 + i)::text, 8, '0'),
    'province', (ARRAY['上海', '北京', '广东', '浙江', '四川'])[(i % 5) + 1],
    'city', (ARRAY['上海', '北京', '深圳', '杭州', '成都'])[(i % 5) + 1],
    'detail', '演示路 ' || (i % 300) || ' 号 ' || ((i % 20) + 1) || ' 室',
    'postal_code', lpad((200000 + i % 700000)::text, 6, '0')
  ),
  (ARRAY['web', 'app', 'mini_program', 'api'])[(i % 4) + 1],
  round(((i * 17) % 10000 / 100.0)::numeric, 2),
  CASE WHEN i % 333 = 0 THEN '请优先处理；演示异常高价值订单' END,
  clock_timestamp() - ((i % 180) * interval '1 day') - ((i % 86400) * interval '1 second'),
  CASE WHEN i % 20 NOT IN (0, 1) THEN clock_timestamp() - ((i % 180) * interval '1 day') + interval '10 minutes' END,
  CASE WHEN i % 20 = 0 THEN clock_timestamp() - ((i % 180) * interval '1 day') + interval '30 minutes' END,
  clock_timestamp() - ((i % 30) * interval '1 day')
FROM generate_series(1, 20000) AS g(i);

INSERT INTO commerce.order_items (
  order_id, variant_id, product_name_snapshot, sku_snapshot, quantity,
  unit_price, discount_amount, attributes, created_at
)
SELECT
  o.order_id,
  v.variant_id,
  p.product_name,
  v.variant_sku,
  1 + ((o.order_id + item.n) % 3),
  round((p.base_price + v.price_delta)::numeric, 2),
  CASE
    WHEN (o.order_id + item.n) % 11 = 0
      THEN round(((p.base_price + v.price_delta) * (1 + ((o.order_id + item.n) % 3)) * 0.05)::numeric, 2)
    ELSE 0
  END,
  jsonb_build_object('gift_wrap', (o.order_id + item.n) % 13 = 0, 'source', 'order_snapshot'),
  o.ordered_at
FROM commerce.orders AS o
CROSS JOIN LATERAL generate_series(1, 3) AS item(n)
JOIN catalog.product_variants AS v
  ON v.variant_id = (((o.order_id * 3 + item.n * 17) - 1) % 6000) + 1
JOIN catalog.products AS p ON p.product_id = v.product_id;

WITH totals AS (
  SELECT order_id, sum(line_total) AS item_total
  FROM commerce.order_items
  GROUP BY order_id
)
UPDATE commerce.orders AS o
SET
  subtotal_amount = totals.item_total,
  discount_amount = CASE WHEN o.order_id % 7 = 0 THEN round((totals.item_total * 0.08)::numeric, 2) ELSE 0 END,
  shipping_fee = CASE WHEN totals.item_total >= 199 THEN 0 ELSE 12 END,
  tax_amount = round((
    (totals.item_total - CASE WHEN o.order_id % 7 = 0 THEN totals.item_total * 0.08 ELSE 0 END) * 0.06
  )::numeric, 2)
FROM totals
WHERE totals.order_id = o.order_id;

INSERT INTO commerce.payments (
  payment_no, order_id, provider, status, amount, transaction_id,
  request_payload, response_payload, paid_at, refunded_at, created_at
)
SELECT
  'PAY-' || lpad(o.order_id::text, 10, '0'),
  o.order_id,
  (ARRAY['alipay', 'wechat_pay', 'unionpay', 'stripe'])[(o.order_id % 4) + 1],
  (CASE
    WHEN o.status = 'pending' THEN 'pending'
    WHEN o.status = 'cancelled' THEN 'failed'
    WHEN o.status = 'refunded' THEN 'refunded'
    WHEN o.status = 'partially_refunded' THEN 'partially_refunded'
    ELSE 'succeeded'
  END)::commerce.payment_status,
  o.total_amount,
  CASE WHEN o.status NOT IN ('pending', 'cancelled') THEN 'TXN-' || md5(o.order_no) END,
  jsonb_build_object('order_no', o.order_no, 'amount', o.total_amount, 'currency', o.currency),
  jsonb_build_object('provider_code', CASE WHEN o.status = 'cancelled' THEN 'DECLINED' ELSE 'SUCCESS' END),
  o.paid_at,
  CASE WHEN o.status IN ('refunded', 'partially_refunded') THEN o.paid_at + interval '5 days' END,
  o.ordered_at + interval '2 minutes'
FROM commerce.orders AS o;

INSERT INTO commerce.shipments (
  shipment_no, order_id, warehouse_id, carrier, tracking_no, status,
  package_info, route_events, shipped_at, delivered_at, updated_at
)
SELECT
  'SHP-' || lpad(o.order_id::text, 10, '0'),
  o.order_id,
  ((o.order_id - 1) % 5) + 1,
  (ARRAY['顺丰', '京东物流', '中通', '跨越速运'])[(o.order_id % 4) + 1],
  'TRK' || lpad(o.order_id::text, 14, '0'),
  (CASE
    WHEN o.status IN ('completed', 'refunded', 'partially_refunded') THEN 'delivered'
    WHEN o.order_id % 97 = 0 THEN 'exception'
    ELSE 'in_transit'
  END)::commerce.shipment_status,
  jsonb_build_object('weight_grams', 500 + (o.order_id % 5000), 'box_count', 1 + (o.order_id % 3)),
  jsonb_build_array(
    jsonb_build_object('status', 'picked', 'at', o.paid_at + interval '4 hours'),
    jsonb_build_object('status', 'in_transit', 'at', o.paid_at + interval '1 day')
  ),
  o.paid_at + interval '4 hours',
  CASE WHEN o.status IN ('completed', 'refunded', 'partially_refunded') THEN o.paid_at + interval '3 days' END,
  greatest(o.updated_at, o.paid_at + interval '1 day')
FROM commerce.orders AS o
WHERE o.status IN ('shipped', 'completed', 'refunded', 'partially_refunded');

INSERT INTO commerce.refunds (
  refund_no, order_id, payment_id, order_item_id, status, reason_code,
  amount, evidence, requested_at, completed_at
)
SELECT
  'REF-' || lpad(o.order_id::text, 10, '0'),
  o.order_id,
  p.payment_id,
  CASE WHEN o.status = 'partially_refunded' THEN oi.order_item_id END,
  'completed'::commerce.refund_status,
  (ARRAY['quality_issue', 'wrong_item', 'late_delivery', 'changed_mind'])[(o.order_id % 4) + 1],
  CASE WHEN o.status = 'refunded' THEN o.total_amount ELSE least(oi.line_total, o.total_amount) END,
  jsonb_build_array(jsonb_build_object('type', 'image', 'url', 'https://example.invalid/evidence/' || o.order_id)),
  o.paid_at + interval '4 days',
  o.paid_at + interval '5 days'
FROM commerce.orders AS o
JOIN commerce.payments AS p ON p.order_id = o.order_id
JOIN LATERAL (
  SELECT order_item_id, line_total
  FROM commerce.order_items
  WHERE order_id = o.order_id
  ORDER BY order_item_id
  LIMIT 1
) AS oi ON true
WHERE o.status IN ('refunded', 'partially_refunded');

INSERT INTO commerce.promotions (
  promo_code, promotion_name, promotion_type, rules, starts_at, ends_at,
  budget_amount, used_count, active
)
SELECT
  'PROMO-' || i,
  '演示营销活动-' || i,
  (ARRAY['percentage', 'fixed', 'bundle', 'free_shipping'])[(i % 4) + 1],
  jsonb_build_object(
    'min_order_amount', 99 + i * 10,
    'discount_value', CASE WHEN i % 4 = 0 THEN 0 ELSE 5 + (i % 30) END,
    'eligible_levels', jsonb_build_array('standard', 'gold', 'vip'),
    'category_ids', jsonb_build_array(11 + (i % 20))
  ),
  clock_timestamp() - ((i % 20) * interval '1 day'),
  clock_timestamp() + ((30 + i) * interval '1 day'),
  50000 + i * 10000,
  i * 137,
  i % 9 <> 0
FROM generate_series(1, 24) AS g(i);

WITH source AS (
  SELECT
    i,
    (ARRAY['commerce.order.events', 'commerce.payment.events', 'iam.login.events', 'inventory.cdc'])[(i % 4) + 1] AS topic,
    i % 12 AS partition_no,
    (i / 12)::bigint AS offset_no,
    (ARRAY['order_created', 'payment_succeeded', 'user_login', 'inventory_changed'])[(i % 4) + 1] AS event_type,
    clock_timestamp() - ((i % 30) * interval '1 day') - ((i % 86400) * interval '1 second') AS event_at
  FROM generate_series(1, 50000) AS g(i)
), shaped AS (
  SELECT
    *,
    jsonb_build_object(
      'event_id', CASE WHEN i IN (200, 201) THEN 'evt-duplicate-200' ELSE 'evt-' || i END,
      'event_type', event_type,
      'event_time', CASE WHEN i % 10001 = 0 THEN 'not-a-date' ELSE to_char(event_at, 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') END,
      'trace_id', md5('trace-' || i::text),
      'source', 'schemanaut-demo',
      'payload', CASE event_type
        WHEN 'order_created' THEN jsonb_build_object(
          'order_id', ((i - 1) % 20000) + 1,
          'user_id', ((i - 1) % 5000) + 1,
          'amount', CASE WHEN i % 8888 = 0 THEN to_jsonb('oops'::text) ELSE to_jsonb(round((100 + i % 5000)::numeric, 2)) END,
          'currency', 'CNY'
        )
        WHEN 'payment_succeeded' THEN jsonb_build_object(
          'payment_id', ((i - 1) % 20000) + 1,
          'provider', (ARRAY['alipay', 'wechat_pay', 'unionpay'])[(i % 3) + 1],
          'latency_ms', CASE WHEN i % 7777 = 0 THEN to_jsonb('timeout'::text) ELSE to_jsonb(20 + (i % 900)) END
        )
        WHEN 'user_login' THEN jsonb_build_object(
          'user_id', ((i - 1) % 5000) + 1,
          'success', i % 17 <> 0,
          'ip', '172.16.' || (i % 250) || '.' || ((i * 7) % 250)
        )
        ELSE jsonb_build_object(
          'variant_id', ((i - 1) % 6000) + 1,
          'warehouse_id', ((i - 1) % 5) + 1,
          'delta', (i % 21) - 10,
          'after_quantity', i % 500
        )
      END
    ) AS base_value
  FROM source
)
INSERT INTO streaming.raw_kafka_events (
  topic, partition_no, offset_no, event_key, event_type, headers, value,
  event_time, ingested_at, schema_version, parse_status
)
SELECT
  topic,
  partition_no,
  offset_no,
  CASE WHEN i % 997 = 0 THEN NULL ELSE event_type || '-' || ((i - 1) % 5000 + 1) END,
  event_type,
  jsonb_build_object(
    'content-type', 'application/json',
    'x-trace-id', md5('trace-' || i::text),
    'producer', CASE WHEN i % 2 = 0 THEN 'java-order-service' ELSE 'go-stream-worker' END
  ),
  CASE WHEN i % 10000 = 0 THEN base_value - 'event_id' ELSE base_value END,
  CASE WHEN i % 10001 = 0 THEN NULL ELSE event_at END,
  event_at + ((i % 8000) * interval '1 millisecond'),
  CASE WHEN i % 13 = 0 THEN 2 ELSE 1 END,
  CASE
    WHEN i % 10001 = 0
      OR (event_type = 'order_created' AND i % 8888 = 0)
      OR (event_type = 'payment_succeeded' AND i % 7777 = 0)
      THEN 'invalid'
    WHEN i % 10000 = 0 THEN 'partial'
    WHEN i = 201 THEN 'duplicate'
    ELSE 'valid'
  END
FROM shaped;

INSERT INTO streaming.consumer_offsets (
  consumer_group, topic, partition_no, committed_offset, high_watermark,
  consumer_instance, updated_at
)
SELECT
  consumer_group,
  topic,
  partition_no,
  3900 + partition_no * 7 - CASE WHEN consumer_group = 'analytics-sink' THEN partition_no * 13 ELSE 0 END,
  4167,
  consumer_group || '-worker-' || (partition_no % 4),
  clock_timestamp() - ((partition_no % 15) * interval '1 minute')
FROM (VALUES
  ('order-sync', 'commerce.order.events'),
  ('analytics-sink', 'commerce.order.events'),
  ('risk-engine', 'iam.login.events')
) AS groups(consumer_group, topic)
CROSS JOIN generate_series(0, 11) AS p(partition_no);

INSERT INTO streaming.dead_letter_events (
  source_event_id, source_topic, error_code, error_message, retry_count,
  payload, first_seen_at, last_retry_at, resolved_at
)
SELECT
  kafka_event_id,
  topic,
  CASE
    WHEN value ->> 'event_id' IS NULL THEN 'MISSING_EVENT_ID'
    WHEN event_time IS NULL THEN 'INVALID_EVENT_TIME'
    ELSE 'PAYLOAD_TYPE_MISMATCH'
  END,
  CASE
    WHEN value ->> 'event_id' IS NULL THEN 'Required event_id is absent'
    WHEN event_time IS NULL THEN 'event_time cannot be parsed as timestamptz'
    ELSE 'Payload field does not match the registered schema'
  END,
  kafka_event_id % 6,
  value,
  ingested_at,
  ingested_at + ((kafka_event_id % 6) * interval '10 minutes'),
  CASE WHEN kafka_event_id % 5 = 0 THEN ingested_at + interval '2 hours' END
FROM streaming.raw_kafka_events
WHERE parse_status <> 'valid';

INSERT INTO analytics.daily_product_metrics (
  metric_date, product_id, view_count, cart_count, order_count, units_sold,
  gross_revenue, refund_amount, updated_at
)
SELECT
  current_date - day_no,
  product_id,
  100 + ((product_id * 17 + day_no * 31) % 10000),
  10 + ((product_id * 13 + day_no * 7) % 900),
  2 + ((product_id * 11 + day_no * 5) % 180),
  3 + ((product_id * 19 + day_no * 3) % 300),
  round((500 + (product_id * 37 + day_no * 101) % 50000)::numeric, 2),
  round(((product_id * 7 + day_no * 13) % 3000)::numeric, 2),
  clock_timestamp()
FROM generate_series(0, 89) AS d(day_no)
CROSS JOIN generate_series(1, 100) AS p(product_id);

CREATE VIEW analytics.daily_sales_summary AS
SELECT
  o.ordered_at::date AS order_date,
  o.channel,
  count(*) AS order_count,
  count(*) FILTER (WHERE o.status = 'completed') AS completed_orders,
  count(*) FILTER (WHERE o.status = 'cancelled') AS cancelled_orders,
  round(sum(o.total_amount), 2) AS gross_merchandise_value,
  round(avg(o.total_amount), 2) AS average_order_value,
  round(sum(r.amount), 2) AS refund_amount
FROM commerce.orders AS o
LEFT JOIN commerce.refunds AS r ON r.order_id = o.order_id
GROUP BY o.ordered_at::date, o.channel;

CREATE VIEW analytics.customer_order_360 AS
WITH order_stats AS (
  SELECT
    user_id,
    count(*) AS order_count,
    count(*) FILTER (WHERE status = 'completed') AS completed_order_count,
    round(sum(total_amount), 2) AS lifetime_order_amount,
    max(ordered_at) AS last_order_at
  FROM commerce.orders
  GROUP BY user_id
), login_stats AS (
  SELECT
    user_id,
    count(*) FILTER (WHERE NOT success) AS failed_login_count_90d
  FROM iam.login_events
  WHERE occurred_at >= clock_timestamp() - interval '90 days'
  GROUP BY user_id
)
SELECT
  u.user_id,
  u.email,
  u.display_name,
  u.status AS user_status,
  u.profile ->> 'level' AS member_level,
  coalesce(os.order_count, 0) AS order_count,
  coalesce(os.completed_order_count, 0) AS completed_order_count,
  coalesce(os.lifetime_order_amount, 0) AS lifetime_order_amount,
  os.last_order_at,
  coalesce(ls.failed_login_count_90d, 0) AS failed_login_count_90d
FROM iam.users AS u
LEFT JOIN order_stats AS os ON os.user_id = u.user_id
LEFT JOIN login_stats AS ls ON ls.user_id = u.user_id;

CREATE VIEW streaming.kafka_event_quality AS
SELECT
  topic,
  event_type,
  parse_status,
  count(*) AS event_count,
  min(event_time) AS first_event_at,
  max(event_time) AS last_event_at,
  round(avg(extract(epoch FROM (ingested_at - event_time)) * 1000)::numeric, 2) AS avg_ingest_latency_ms
FROM streaming.raw_kafka_events
GROUP BY topic, event_type, parse_status;

COMMENT ON DATABASE schemanaut_demo IS 'SchemaNaut complex e-commerce, identity, Kafka and analytics demonstration database';
COMMENT ON SCHEMA iam IS 'User identity, authorization, sessions and login audit domain';
COMMENT ON SCHEMA catalog IS 'Product catalog and variant domain';
COMMENT ON SCHEMA commerce IS 'Orders, inventory, payment, fulfillment, refund and promotion domain';
COMMENT ON SCHEMA streaming IS 'Kafka-style raw events, consumer offsets and dead-letter queue';
COMMENT ON SCHEMA analytics IS 'Pre-aggregated metrics and cross-domain analytical views';
COMMENT ON TABLE streaming.raw_kafka_events IS 'Kafka envelope table; value is intentionally heterogeneous JSONB and includes dirty examples';
COMMENT ON COLUMN streaming.raw_kafka_events.value IS 'Raw producer JSON payload. Parse fields only after inspecting event_type and payload shape';
COMMENT ON TABLE commerce.orders IS 'Order header. total_amount is generated from subtotal, discount, shipping fee and tax';
COMMENT ON TABLE iam.login_events IS 'Authentication and logout audit events, including failed logins and geo/device context';

COMMIT;

ANALYZE iam.users;
ANALYZE iam.login_events;
ANALYZE catalog.products;
ANALYZE catalog.product_variants;
ANALYZE commerce.inventory;
ANALYZE commerce.orders;
ANALYZE commerce.order_items;
ANALYZE commerce.payments;
ANALYZE commerce.shipments;
ANALYZE streaming.raw_kafka_events;
ANALYZE streaming.consumer_offsets;
ANALYZE analytics.daily_product_metrics;

SELECT
  current_database() AS database_name,
  (SELECT count(*) FROM pg_catalog.pg_tables WHERE schemaname IN ('iam', 'catalog', 'commerce', 'streaming', 'analytics')) AS table_count,
  (SELECT count(*) FROM iam.users) AS users,
  (SELECT count(*) FROM commerce.orders) AS orders,
  (SELECT count(*) FROM commerce.order_items) AS order_items,
  (SELECT count(*) FROM streaming.raw_kafka_events) AS kafka_events;
