import type { AgentCapabilityModuleRegistration } from '@dbagent/core-agent';
import { createCommandCapabilityRegistration } from './command-module.js';
import type { FirstPartyCapabilityHost } from './types.js';
import { hasControlCodePoint } from './input-validation.js';
const networkRead = Object.freeze({ access: 'external' as const, recoveryClass: 'read' as const, dangerLevel: 'medium' as const, actions: Object.freeze(['read', 'network'] as const), network: true, externalWrite: false, destructive: false, admin: false, unknownRisk: false });
const externalWrite = Object.freeze({ access: 'external' as const, recoveryClass: 'non_idempotent' as const, dangerLevel: 'high' as const, actions: Object.freeze(['write', 'network'] as const), network: true, externalWrite: true, destructive: false, admin: false, unknownRisk: false });
const empty = { type: 'object', additionalProperties: false } as const;
const listInput = { type: 'object', additionalProperties: false, properties: { limit: { type: 'integer', minimum: 1, maximum: 100 } } } as const;
const numberInput = { type: 'object', additionalProperties: false, required: ['number'], properties: { number: { type: 'integer', minimum: 1, maximum: 1_000_000 } } } as const;
const createInput = { type: 'object', additionalProperties: false, required: ['title', 'body', 'base', 'head'], properties: { title: { type: 'string', minLength: 1, maxLength: 512 }, body: { type: 'string', minLength: 1, maxLength: 16384 }, base: { type: 'string', minLength: 1, maxLength: 256 }, head: { type: 'string', minLength: 1, maxLength: 256 }, draft: { type: 'boolean' } } } as const;
/** Forge delegates authentication and repository selection to an already configured gh or glab CLI. */
export function createForgeCapability(host: FirstPartyCapabilityHost): AgentCapabilityModuleRegistration { return createCommandCapabilityRegistration({ moduleId: 'schemanaut.forge', capabilityId: 'schemanaut.forge', instanceId: 'first-party-forge', version: '1.0.0', description: 'Forge operations using an externally authenticated gh or glab CLI.', executables: ['gh', 'glab'], selection: 'choice_required', operations: [
  { name: 'forge_status', description: 'Read the current forge repository status.', inputSchema: empty, argv: (_input, provider) => choose(provider, ['repo', 'view', '--json', 'nameWithOwner,url,viewerPermission'], ['repo', 'view', '--output', 'json']), permission: networkRead, output: 'json' },
  { name: 'forge_issue_list', description: 'List bounded forge issues.', inputSchema: listInput, argv: (input, provider) => choose(provider, ['issue', 'list', '--limit', String(integer(input.limit, 20, 1, 100)), '--json', 'number,title,state,url'], ['issue', 'list', '--per-page', String(integer(input.limit, 20, 1, 100)), '--output', 'json']), permission: networkRead, output: 'json' },
  { name: 'forge_issue_view', description: 'Read one forge issue.', inputSchema: numberInput, argv: (input, provider) => choose(provider, ['issue', 'view', String(integer(input.number, 0, 1, 1_000_000)), '--json', 'number,title,body,state,url,author,labels'], ['issue', 'view', String(integer(input.number, 0, 1, 1_000_000)), '--output', 'json']), permission: networkRead, output: 'json' },
  { name: 'forge_pr_list', description: 'List bounded forge pull requests or merge requests.', inputSchema: listInput, argv: (input, provider) => choose(provider, ['pr', 'list', '--limit', String(integer(input.limit, 20, 1, 100)), '--json', 'number,title,state,url,headRefName,baseRefName'], ['mr', 'list', '--per-page', String(integer(input.limit, 20, 1, 100)), '--output', 'json']), permission: networkRead, output: 'json' },
  { name: 'forge_pr_view', description: 'Read one forge pull request or merge request.', inputSchema: numberInput, argv: (input, provider) => choose(provider, ['pr', 'view', String(integer(input.number, 0, 1, 1_000_000)), '--json', 'number,title,body,state,url,headRefName,baseRefName'], ['mr', 'view', String(integer(input.number, 0, 1, 1_000_000)), '--output', 'json']), permission: networkRead, output: 'json' },
  { name: 'forge_checks', description: 'Read checks for the current forge pull request or merge request.', inputSchema: numberInput, argv: (input, provider) => choose(provider, ['pr', 'checks', String(integer(input.number, 0, 1, 1_000_000)), '--json', 'name,state,workflow,link'], ['ci', 'get', `--merge-request=${integer(input.number, 0, 1, 1_000_000)}`, '--output', 'json']), permission: networkRead, output: 'json', allowNonZeroJson: true },
  { name: 'forge_pr_create', description: 'Create a forge pull request or merge request.', inputSchema: createInput, argv: (input, provider) => choose(provider, ['pr', 'create', '--title', required(input.title, 'title', 512), '--body', required(input.body, 'body', 16_384), '--base', required(input.base, 'base', 256), '--head', required(input.head, 'head', 256), ...(input.draft === true ? ['--draft'] : [])], ['mr', 'create', '--title', required(input.title, 'title', 512), '--description', required(input.body, 'body', 16_384), '--target-branch', required(input.base, 'base', 256), '--source-branch', required(input.head, 'head', 256), ...(input.draft === true ? ['--draft'] : [])]), permission: externalWrite, output: 'stable-text' },
] }, host); }
function choose(provider: string, github: readonly string[], gitlab: readonly string[]): readonly string[] { return provider === 'gh' ? github : provider === 'glab' ? gitlab : (() => { throw new TypeError('external forge provider is invalid.'); })(); }
function required(value: unknown, name: string, maximum = 256): string { if (typeof value !== 'string' || !value.trim() || value.length > maximum || hasControlCodePoint(value)) throw new TypeError(`${name} is invalid.`); return value; }
function integer(value: unknown, fallback: number, minimum: number, maximum: number): number { if (value === undefined) return fallback; if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < minimum || value > maximum) throw new TypeError('integer input is invalid.'); return value; }
