import type { AgentCapabilityModuleRegistration } from '@dbagent/core-agent';
import { createCommandCapabilityRegistration } from './command-module.js';
import type { FirstPartyCapabilityHost } from './types.js';
import { hasControlCodePoint } from './input-validation.js';
const read = Object.freeze({ access: 'read' as const, recoveryClass: 'read' as const, dangerLevel: 'safe' as const, actions: Object.freeze(['read'] as const), network: false, externalWrite: false, destructive: false, admin: false, unknownRisk: false });
const write = Object.freeze({ access: 'write' as const, recoveryClass: 'idempotent' as const, dangerLevel: 'high' as const, actions: Object.freeze(['write'] as const), network: false, externalWrite: false, destructive: false, admin: false, unknownRisk: true });
const commit = Object.freeze({ access: 'write' as const, recoveryClass: 'non_idempotent' as const, dangerLevel: 'high' as const, actions: Object.freeze(['write'] as const), network: false, externalWrite: false, destructive: false, admin: false, unknownRisk: true });
const empty = { type: 'object', additionalProperties: false } as const;
const diffInput = { type: 'object', additionalProperties: false, properties: { staged: { type: 'boolean' }, path: { type: 'string', maxLength: 8192 }, context: { type: 'integer', minimum: 0, maximum: 100 } } } as const;
const logInput = { type: 'object', additionalProperties: false, properties: { limit: { type: 'integer', minimum: 1, maximum: 100 } } } as const;
const showInput = { type: 'object', additionalProperties: false, required: ['ref'], properties: { ref: { type: 'string', minLength: 1, maxLength: 256 } } } as const;
const stageInput = { type: 'object', additionalProperties: false, required: ['paths'], properties: { paths: { type: 'array', minItems: 1, maxItems: 64, items: { type: 'string', minLength: 1, maxLength: 8192 } } } } as const;
const commitInput = { type: 'object', additionalProperties: false, required: ['message'], properties: { message: { type: 'string', minLength: 1, maxLength: 4096 } } } as const;
export function createGitCapability(host: FirstPartyCapabilityHost): AgentCapabilityModuleRegistration { return createCommandCapabilityRegistration({ moduleId: 'schemanaut.git', capabilityId: 'schemanaut.git', instanceId: 'first-party-git', version: '1.0.0', description: 'Workspace Git operations using the externally configured git CLI.', executables: ['git'], operations: [
  { name: 'git_status', description: 'Read the current workspace Git status.', inputSchema: empty, argv: () => ['-c', 'core.fsmonitor=false', '--no-optional-locks', '--no-pager', 'status', '--porcelain=v2', '--branch'], permission: read, output: 'stable-text' },
  { name: 'git_diff', description: 'Read a bounded workspace Git diff.', inputSchema: diffInput, argv: input => ['-c', 'core.fsmonitor=false', '--no-optional-locks', '--no-pager', 'diff', ...(input.staged === true ? ['--staged'] : []), `--unified=${integer(input.context, 3, 0, 100)}`, '--no-ext-diff', '--no-textconv', '--', ...(path(input.path) ?? [])], pathInputs: input => path(input.path) ?? [], permission: read, output: 'stable-text' },
  { name: 'git_log', description: 'Read bounded recent workspace Git history.', inputSchema: logInput, argv: input => ['-c', 'core.fsmonitor=false', '--no-optional-locks', '--no-pager', 'log', `--max-count=${integer(input.limit, 20, 1, 100)}`, '--format=%H%x09%an%x09%ad%x09%s', '--date=iso-strict'], permission: read, output: 'stable-text' },
  { name: 'git_show', description: 'Read a Git object by explicit ref.', inputSchema: showInput, argv: input => ['-c', 'core.fsmonitor=false', '--no-optional-locks', '--no-pager', 'show', '--no-ext-diff', '--no-textconv', '--format=fuller', ref(input.ref)], permission: read, output: 'stable-text' },
  { name: 'git_stage', description: 'Stage explicit workspace paths in Git.', inputSchema: stageInput, argv: input => ['-c', 'core.fsmonitor=false', '--no-pager', 'add', '--', ...paths(input.paths)], pathInputs: input => paths(input.paths), permission: write, output: 'stable-text' },
  { name: 'git_commit', description: 'Create one workspace Git commit with an explicit message.', inputSchema: commitInput, argv: input => ['-c', 'core.fsmonitor=false', '--no-pager', 'commit', '-m', required(input.message, 'message', 4096)], permission: commit, output: 'stable-text' },
] }, host); }
function required(value: unknown, name: string, maximum = 256): string { if (typeof value !== 'string' || !value.trim() || value.length > maximum || hasControlCodePoint(value)) throw new TypeError(`${name} is invalid.`); return value; }
function integer(value: unknown, fallback: number, minimum: number, maximum: number): number { if (value === undefined) return fallback; if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < minimum || value > maximum) throw new TypeError('integer input is invalid.'); return value; }
function path(value: unknown): readonly string[] | undefined { return value === undefined ? undefined : [required(value, 'path', 8192)]; }
function paths(value: unknown): readonly string[] { if (!Array.isArray(value) || !value.length || value.length > 64) throw new TypeError('paths are invalid.'); return value.map(item => required(item, 'path', 8192)); }
function ref(value: unknown): string { const result = required(value, 'ref'); if (result.startsWith('-')) throw new TypeError('ref cannot begin with a dash.'); return result; }
