import { describe, expect, it } from 'vitest';
import { buildAlterTablePreview, buildCreateTablePreview } from '../src/index.js';

describe('table designer DDL preview builder', () => {
  it('builds a create table preview with columns, comments, indexes, and foreign keys', () => {
    const preview = buildCreateTablePreview({
      schema: 'public',
      table: 'orders',
      comment: '订单表',
      columns: [
        { name: 'id', dataType: 'bigint', primaryKey: true, identity: true, comment: '主键' },
        { name: 'user_id', dataType: 'bigint', nullable: false },
        { name: 'status', dataType: 'varchar(32)', nullable: false, defaultValue: "'pending'", checkExpression: "status <> ''" },
        { name: 'payload', dataType: 'jsonb', nullable: true },
      ],
      indexes: [{ columns: ['user_id', 'status'] }],
      foreignKeys: [
        {
          columns: ['user_id'],
          references: { table: 'users', columns: ['id'] },
          onDelete: 'cascade',
        },
      ],
    });

    expect(preview.ok).toBe(true);
    if (!preview.ok) return;
    expect(preview.data.requiresConfirmation).toBe(true);
    expect(preview.data.riskLevel).toBe('dangerous');
    expect(preview.data.warnings).toEqual([]);
    expect(preview.data.sql).toBe(
      [
        'create table "public"."orders" (',
        '  "id" bigint generated by default as identity not null,',
        '  "user_id" bigint not null,',
        '  "status" varchar(32) not null default \'pending\' check (status <> \'\'),',
        '  "payload" jsonb,',
        '  primary key ("id")',
        ');',
        "comment on table \"public\".\"orders\" is '订单表';",
        "comment on column \"public\".\"orders\".\"id\" is '主键';",
        'create index "idx_orders_user_id_status" on "public"."orders" using btree ("user_id", "status");',
        'alter table "public"."orders" add constraint "fk_orders_user_id" foreign key ("user_id") references "public"."users" ("id") on delete cascade;',
      ].join('\n'),
    );
  });

  it('warns when a new table has no primary key', () => {
    const preview = buildCreateTablePreview({
      schema: 'public',
      table: 'events',
      columns: [{ name: 'payload', dataType: 'jsonb' }],
    });

    expect(preview.ok).toBe(true);
    if (!preview.ok) return;
    expect(preview.data.warnings).toEqual(['Table has no primary key. Editing rows safely will be limited.']);
  });

  it('builds an alter table preview for adding columns, indexes, foreign keys, and comments', () => {
    const preview = buildAlterTablePreview({
      schema: 'public',
      table: 'orders',
      addColumns: [{ name: 'phone', dataType: 'varchar(32)', nullable: true, comment: "客户'手机号" }],
      addIndexes: [{ name: 'ix_orders_phone', columns: ['phone'], unique: true }],
      addForeignKeys: [
        {
          name: 'fk_orders_phone_owner',
          columns: ['phone'],
          references: { schema: 'crm', table: 'phones', columns: ['phone'] },
          onUpdate: 'cascade',
        },
      ],
      tableComment: '订单主表',
    });

    expect(preview.ok).toBe(true);
    if (!preview.ok) return;
    expect(preview.data.statements).toEqual([
      'alter table "public"."orders" add column "phone" varchar(32);',
      "comment on column \"public\".\"orders\".\"phone\" is '客户''手机号';",
      'create unique index "ix_orders_phone" on "public"."orders" using btree ("phone");',
      'alter table "public"."orders" add constraint "fk_orders_phone_owner" foreign key ("phone") references "crm"."phones" ("phone") on update cascade;',
      "comment on table \"public\".\"orders\" is '订单主表';",
    ]);
  });

  it('rejects unsafe column data type tokens', () => {
    const preview = buildCreateTablePreview({
      schema: 'public',
      table: 'bad',
      columns: [{ name: 'name', dataType: 'text; drop table users' }],
    });

    expect(preview.ok).toBe(false);
    if (preview.ok) return;
    expect(preview.error).toMatchObject({
      code: 'VALIDATION_ERROR',
      message: 'Column data type contains unsafe SQL tokens.',
    });
  });

  it('rejects invalid foreign key definitions before DDL is shown to users', () => {
    const preview = buildAlterTablePreview({
      schema: 'public',
      table: 'orders',
      addForeignKeys: [
        {
          columns: ['user_id', 'tenant_id'],
          references: { table: 'users', columns: ['id'] },
        },
      ],
    });

    expect(preview.ok).toBe(false);
    if (preview.ok) return;
    expect(preview.error).toMatchObject({
      code: 'VALIDATION_ERROR',
      message: 'Foreign key local and referenced column counts must match.',
    });
  });

  it('requires at least one alter table change', () => {
    const preview = buildAlterTablePreview({ schema: 'public', table: 'orders' });

    expect(preview.ok).toBe(false);
    if (preview.ok) return;
    expect(preview.error).toMatchObject({
      code: 'VALIDATION_ERROR',
      message: 'Alter table preview requires at least one change.',
    });
  });
});
